# To run the application in a cloud
version: '3.1'
services:
  sota_api:
    restart: always
    build:
      context: ./sota_api
      dockerfile: docker/Dockerfile
      args:
        TARGET: production 
        RUN_ON_CPU: 1 
    container_name: sota_api_amd
    volumes:
    - /${HOME}/data_prod/sota_api/logs:/data/public/logs
    - ./sota_api/schultz/networks/:/data/networks/

    env_file: ./sota_api/docker/env_prod
    ports:
    - 8001:80
    networks:
    - sota_api_default

networks:
  sota_api_default:
